export default {
	LOGIN_REQUEST:					'LOGIN_REQUEST',
	LOGIN_SUCCESS:					'LOGIN_SUCCESS',
	LOGIN_FAILURE:					'LOGIN_FAILURE',
	REGISTER_REQUEST:				'REGISTER_REQUEST',
	REGISTER_SUCCESS:				'REGISTER_SUCCESS',
	REGISTER_FAILURE:				'REGISTER_FAILURE',
	LOGOUT_SUCCESS:					'LOGOUT_SUCCESS',
	USERS_RECEIVED:         'USERS_RECEIVED',
	USER_CREATED:           'USER_CREATED',
	USER_LOGGED_IN:         'USER_LOGGED_IN',
  CURRENT_USER_RECEIVED:  'CURRENT_USER_RECEIVED',
  FETCHING_PROFILE:       'FETCHING_PROFILE',

  CREATING_SWEEPSTAKE:    'CREATING_SWEEPSTAKE',
  SWEEPSTAKE_CREATED:     'SWEEPSTAKE_CREATED',
  FETCHING_SWEEPSTAKES:   'FETCHING_SWEEPSTAKES',
  SWEEPSTAKES_RECEIVED:   'SWEEPSTAKES_RECEIVED',
  FETCHING_SWEEPSTAKE:    'FETCHING_SWEEPSTAKE',
  SWEEPSTAKE_SELECTED:    'SWEEPSTAKE_SELECTED',
  SWEEPSTAKE_RECEIVED:    'SWEEPSTAKE_RECEIVED',
  SWEEPSTAKE_DELETED:     'SWEEPSTAKE_DELETED',
  GENERATING_SWEEPSTAKE:  'GENERATING_SWEEPSTAKE',
  SWEEPSTAKE_GENERATED:   'SWEEPSTAKE_GENERATED',

  FETCHING_USERS:         'FETCHING_USERS',
  USERS_RECEIVED:         'USERS_RECEIVED',

  FETCHING_COMPETITION:   'FETCHING_COMPETITION',
  FETCHED_COMPETITION:    'FETCHED_COMPETITION',
  ERROR_FETCHING_COMPETITION: 'ERROR_FETCHING_COMPETITION',

  FETCHING_TEAMS:         'FETCHING_TEAMS',
  FETCHED_TEAMS:          'FETCHED_TEAMS',
  ERROR_FETCHING_TEAMS:   'ERROR_FETCHING_TEAMS',

  FAILED_ADD_MEMBER:      'FAILED_ADD_MEMBER',
  MEMBER_ADDED:           'MEMBER_ADDED',

  FETCHED_FIXTURES:       'FETCHED_FIXTURES',

  FETCHING_GROUP_STANDINGS: 'FETCHING_GROUP_STANDINGS',
  FETCHED_GROUP_STANDINGS:  'FETCHED_GROUP_STANDINGS',
  ERROR_FETCHING_GROUP_STANDINGS: 'ERROR_FETCHING_GROUP_STANDINGS',

  POINTS_CALCULATED:      'POINTS_CALCULATED',

  FIXTURE_SNACKBAR_TOGGLED:   'FIXTURE_SNACKBAR_TOGGLED',

  MEMBER_PAID:            'MEMBER_PAID'

}