export default {
	LOGIN_REQUEST:					'LOGIN_REQUEST',
	LOGIN_SUCCESS:					'LOGIN_SUCCESS',
	LOGIN_FAILURE:					'LOGIN_FAILURE',
	REGISTER_REQUEST:				'REGISTER_REQUEST',
	REGISTER_SUCCESS:				'REGISTER_SUCCESS',
	REGISTER_FAILURE:				'REGISTER_FAILURE',
	LOGOUT_SUCCESS:					'LOGOUT_SUCCESS',
	USERS_RECEIVED:         'USERS_RECEIVED',
	USER_CREATED:           'USER_CREATED',
	USER_LOGGED_IN:         'USER_LOGGED_IN',
  CURRENT_USER_RECEIVED:  'CURRENT_USER_RECEIVED',
  FETCHING_PROFILE:       'FETCHING_PROFILE',

  CREATING_SWEEPSTAKE:    'CREATING_SWEEPSTAKE',
  SWEEPSTAKE_CREATED:     'SWEEPSTAKE_CREATED',
  FETCHING_SWEEPSTAKES:   'FETCHING_SWEEPSTAKES',
  SWEEPSTAKES_RECEIVED:   'SWEEPSTAKES_RECEIVED',
  SWEEPSTAKE_DELETED:     'SWEEPSTAKE_DELETED'

}