export default {

	USERS_RECEIVED:         'USERS_RECEIVED',
	USER_CREATED:           'USER_CREATED',
	USER_LOGGED_IN:         'USER_LOGGED_IN',
  CURRENT_USER_RECEIVED:  'CURRENT_USER_RECEIVED',
  FETCHING_PROFILE:       'FETCHING_PROFILE',

  CREATING_SWEEPSTAKE:    'CREATING_SWEEPSTAKE',
  SWEEPSTAKE_CREATED:     'SWEEPSTAKE_CREATED',
  FETCHING_SWEEPSTAKES:   'FETCHING_SWEEPSTAKES',
  SWEEPSTAKES_RECEIVED:   'SWEEPSTAKES_RECEIVED',
  SWEEPSTAKE_DELETED:     'SWEEPSTAKE_DELETED'

}